# Unique project identifier
sonar.projectKey=Wanderwise-Backend

# Path to the source code (relative to this file)
sonar.sources=app
sonar.python.version=3

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Exclusions (Optional but good practice to keep here)
sonar.exclusions=env/**,venv/**,tests/**,**/__pycache__/**,*.xml

# Quality Gates & Coverage
sonar.python.coverage.reportPaths=coverage.xml
sonar.scm.disabled=true